services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: devops-api:latest
    container_name: devops-api
    ports:
      - "5000:5000"
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api
